### ISSUE TITLE
Bug Report: Back Arrow Key Global Dashboard (Pedro)

### ISSUE THREAD

**Issue by TylerLo416** [Center-For-Energy-TEC-App/Tec-App#77]
From pedro: "The back arrow key on the global dashboard doesn't work for me"

- [ ] See if you can replicate this bug on your device, or connect with Pedro to see if the issue is user error, or device specific. Fix if there's a bug.

**Comment by yotzkim** [comment]
I checked it out, it does allow you to use the back arrow key and the code is just an SVG that has an onPress, so I think the issue is maybe the range of the svg/onPress could be a little small. What I can do is just put another TouchableOpacity around the back arrow and have that have a wider range so that the back button press is registered
